version: '3.9'

networks:
  default:
    driver: bridge

volumes:
  default:
    driver: local

services:
  db:
    image: postgres:latest
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - ${DB_PORT}
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DEFAULT_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DEFAULT_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - default:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  registry:
    env_file:
      - ./apps/registry/.env
      - .env
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    container_name: security-registry
    command: pnpm start:dev registry
    restart: unless-stopped
    expose:
      - "${REGISTRY_PORT}"
    volumes:
      - ./apps/registry:/usr/src/apps/apps/registry
      - /usr/src/apps/node_modules

  dwellings:
    env_file:
      - ./apps/dwellings/.env
      - .env
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    container_name: security-dwellings
    command: pnpm start:dev dwellings
    restart: unless-stopped
    expose:
      - '${DWELLINGS_PORT}'
    volumes:
      - ./apps/dwellings:/usr/src/apps/apps/dwellings
      - /usr/src/apps/node_modules
    depends_on:
      - db
      - registry

  residents:
    env_file:
      - ./apps/residents/.env
      - .env
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    container_name: security-residents
    command: pnpm start:dev residents
    restart: unless-stopped
    expose:
      - "${RESIDENTS_PORT}"
    volumes:
      - ./apps/residents:/usr/src/apps/apps/residents
      - /usr/src/apps/node_modules
    depends_on:
      - registry

  gateway:
    env_file:
      - ./apps/gateway/.env
      - .env
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    container_name: security-gateway
    command: pnpm start:dev gateway
    restart: unless-stopped
    expose:
      - '${GATEWAY_PORT}'
    volumes:
      - ./apps/gateway:/usr/src/apps/apps/gateway
      - /usr/src/apps/node_modules
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    depends_on:
      - registry
      - dwellings
      - residents
